### ISSUE TITLE
Manga training model

### ISSUE THREAD

**Issue by webcooltz** [PySimpleGUI/PySimpleGUI-Photo-Colorizer#2]
## Manga

I think it would be awesome to train a model to colorize manga. I would love to help but I'm a bit of a noob with Python. If anyone knows how to help, please let me know.

Thanks!

## Thank you
I really appreciate this. It has helped me colorize old family history photos and see a clearer image of the past. Thank you for this.

**Comment by PySimpleGUI** [comment]
You're quite welcome!

I can't take any credit beyond the front-end GUI.  The fine folks at PyImageSearch are the machine learning wizards behind the heavy-lifting portion of the code.  

https://www.pyimagesearch.com/2019/02/25/black-and-white-image-colorization-with-opencv-and-deep-learning/

I _think_ that the training data came from here:

http://richzhang.github.io/colorization/

I really like this program.  It's fun to run old photos, historical photos, family photos through it and see what comes out.  I was shocked to see the reflection of **_a piece of wood_** in a mirror get the correct brown color in one of the test photos.  It was a tiny little part that was reflected yet the algorithm picked it out and colored it correctly.

Sometimes these machine learning results seem like magic.

**Comment by PySimpleGUI** [comment]
Closing this issue as it's been quite a while and I think I provided the best answer I can.

There should be a number of articles out there at this point on how to train a colorization model.  It's beyond the scope of this project.  The focus here is on how to add a user interface to an algorithm such as the Zhang model to a graphical interface so that it's accessible to a wider audience.
